[package]
name = "scylladb-drivers-benchmarker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"
sqlite = "0.37.0"
serde_yml = "0.0.12"
serde_json = "1"
serde = { version = "1.0.228", features = ["derive"] }
plotters = "0.3.3"
shell-words = "1.1.0"
justerror = "1.1.0"
thiserror = "2.0.17"

[dev-dependencies]
assert_cmd = "2.1.1"
tempfile = "3.23.0"
plotters = "0.3.3"
